<a href="https://colab.research.google.com/github/abhayak759/AI-ML-Projects/blob/main/Over_sampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('/content/Churn_Modelling.csv')

In [ ]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df.shape

(10000, 14)

In [ ]:
df.Exited.value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [ ]:
df.drop(['RowNumber', 'CustomerId', 'Surname'], axis='columns', inplace = True)

In [ ]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df.Geography.value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [ ]:
df.value_counts()

CreditScore  Geography  Gender  Age  Tenure  Balance    NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited
350          France     Female  40   0       111098.85  1              1          1               172321.21        1         1
695          France     Male    36   4       161533.00  1              1          0               100940.91        0         1
                        Female  36   2       0.00       2              0          1               167749.54        0         1
                                42   0       0.00       2              0          1               140724.64        0         1
                                     5       0.00       1              0          1               72172.13         1         1
                                                                                                                            ..
608          France     Male    42   5       0.00       2              1          0               178504.29        0         1
                                     10      163548.07  1              1          0               38866.85         0         1
                                50   6       0.00       1              1          0               93568.77         1         1
                                59   1       0.00       1              1          0               70649.64         1         1
850          Spain      Male    71   10      69608.14   1              1          0               97893.40         1         1
Name: count, Length: 10000, dtype: int64

In [ ]:
df.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df=pd.get_dummies(df, ['Geography', 'Gender'], dtype=int)

In [ ]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,1,0,0,1,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,0,1,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,1,0,0,1,0
3,699,39,1,0.00,2,0,0,93826.63,0,1,0,0,1,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,1,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,1,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,1,0,0,1,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0,1,0,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,1,0,0,1,0

In [ ]:
X=df.drop(['Exited'], axis=1)
y=df['Exited']

In [ ]:
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,1,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,1,0
3,699,39,1,0.00,2,0,0,93826.63,1,0,0,1,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,1,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,1,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,0,0,1,0
9998,772,42,3,75075.31,2,1,0,92888.52,0,1,0,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,1,0,0,1,0

In [ ]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X_train.shape

(8000, 13)

In [ ]:
X_test.shape

(2000, 13)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)

In [ ]:
print(X_train)

[[ 0.35649971 -0.6557859   0.34567966 ... -0.57638802 -0.91324755
   0.91324755]
 [-0.20389777  0.29493847 -0.3483691  ... -0.57638802 -0.91324755
   0.91324755]
 [-0.96147213 -1.41636539 -0.69539349 ...  1.73494238 -0.91324755
   0.91324755]
 ...
 [ 0.86500853 -0.08535128 -1.38944225 ... -0.57638802  1.09499335
  -1.09499335]
 [ 0.15932282  0.3900109   1.03972843 ... -0.57638802 -0.91324755
   0.91324755]
 [ 0.47065475  1.15059039 -1.38944225 ... -0.57638802 -0.91324755
   0.91324755]]

In [ ]:
X_test=sc.transform(X_test)

In [ ]:
from imblearn.over_sampling import RandomOverSampler
ros=RandomOverSampler()
X_train, y_train=ros.fit_resample(X_train, y_train)

In [ ]:
from collections import Counter
Counter(y_train)

Counter({0: 6356, 1: 6356})

In [ ]:
y_train.value_counts()

Exited
0    6356
1    6356
Name: count, dtype: int64

In [ ]:
import tensorflow
from tensorflow import keras
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
def ANN(X_train, y_train, X_test, y_test, loss):
    model = keras.Sequential([
        keras.layers.Dense(13, input_dim=13, activation='relu'),
        keras.layers.Dense(10, activation='relu'),
        keras.layers.Dense(1, activation='sigmoid')
    ])

    model.compile(optimizer='adam', loss=loss, metrics=['accuracy'])


    model.fit(X_train, y_train, epochs=100)

    print(model.evaluate(X_test, y_test))

    y_preds = model.predict(X_test)
    y_preds = np.round(y_preds)

    print("Classification Report: \n", classification_report(y_test, y_preds))

    return y_preds

In [ ]:
y_preds = ANN(X_train, y_train, X_test, y_test, 'binary_crossentropy')

Epoch 1/100
398/398 [==============================] - 3s 5ms/step - loss: 0.6095 - accuracy: 0.6610
Epoch 2/100
398/398 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7306
Epoch 3/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4957 - accuracy: 0.7563
Epoch 4/100
398/398 [==============================] - 1s 3ms/step - loss: 0.4752 - accuracy: 0.7650
Epoch 5/100
398/398 [==============================] - 1s 3ms/step - loss: 0.4656 - accuracy: 0.7740
Epoch 6/100
398/398 [==============================] - 2s 4ms/step - loss: 0.4603 - accuracy: 0.7775
Epoch 7/100
398/398 [==============================] - 1s 3ms/step - loss: 0.4565 - accuracy: 0.7793
Epoch 8/100
398/398 [==============================] - 3s 7ms/step - loss: 0.4543 - accuracy: 0.7811
Epoch 9/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4523 - accuracy: 0.7812
Epoch 10/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4507 - accuracy: 0.7831
Epoch 11/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4492 - accuracy: 0.7832
Epoch 12/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4475 - accuracy: 0.7820
Epoch 13/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4468 - accuracy: 0.7861
Epoch 14/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4456 - accuracy: 0.7882
Epoch 15/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4446 - accuracy: 0.7846
Epoch 16/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4433 - accuracy: 0.7869
Epoch 17/100
398/398 [==============================] - 1s 3ms/step - loss: 0.4422 - accuracy: 0.7885
Epoch 18/100
398/398 [==============================] - 1s 3ms/step - loss: 0.4415 - accuracy: 0.7879
Epoch 19/100
398/398 [==============================] - 1s 3ms/step - loss: 0.4409 - accuracy: 0.7899
Epoch 20/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4405 - accuracy: 0.7903
Epoch 21/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4388 - accuracy: 0.7912
Epoch 22/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4384 - accuracy: 0.7908
Epoch 23/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4370 - accuracy: 0.7915
Epoch 24/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4365 - accuracy: 0.7906
Epoch 25/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4355 - accuracy: 0.7903
Epoch 26/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4344 - accuracy: 0.7911
Epoch 27/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4338 - accuracy: 0.7930
Epoch 28/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4332 - accuracy: 0.7909
Epoch 29/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4324 - accuracy: 0.7939
Epoch 30/100
398/398 [==============================] - 1s 4ms/step - loss: 0.4319 - accuracy: 0.7938
Epoch 31/100
398/398 [==============================] - 1s 4ms/step - loss: 0.4309 - accuracy: 0.7935
Epoch 32/100
398/398 [==============================] - 1s 3ms/step - loss: 0.4299 - accuracy: 0.7917
Epoch 33/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4293 - accuracy: 0.7926
Epoch 34/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4291 - accuracy: 0.7940
Epoch 35/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4279 - accuracy: 0.7944
Epoch 36/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4280 - accuracy: 0.7948
Epoch 37/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4271 - accuracy: 0.7963
Epoch 38/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4273 - accuracy: 0.7950
Epoch 39/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4260 - accuracy: 0.7941
Epoch 40/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4261 - accuracy: 0.7936
Epoch 41/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4251 - accuracy: 0.7939
Epoch 42/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4248 - accuracy: 0.7936
Epoch 43/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4241 - accuracy: 0.7941
Epoch 44/100
398/398 [==============================] - 1s 3ms/step - loss: 0.4241 - accuracy: 0.7958
Epoch 45/100
398/398 [==============================] - 1s 3ms/step - loss: 0.4231 - accuracy: 0.7976
Epoch 46/100
398/398 [==============================] - 1s 4ms/step - loss: 0.4228 - accuracy: 0.7969
Epoch 47/100
398/398 [==============================] - 2s 4ms/step - loss: 0.4226 - accuracy: 0.7958
Epoch 48/100
398/398 [==============================] - 1s 3ms/step - loss: 0.4223 - accuracy: 0.7944
Epoch 49/100
398/398 [==============================] - 1s 3ms/step - loss: 0.4222 - accuracy: 0.7977
Epoch 50/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4216 - accuracy: 0.7970
Epoch 51/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4211 - accuracy: 0.7983
Epoch 52/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4208 - accuracy: 0.7984
Epoch 53/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4203 - accuracy: 0.7983
Epoch 54/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4198 - accuracy: 0.7990
Epoch 55/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4200 - accuracy: 0.7973
Epoch 56/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4198 - accuracy: 0.7989
Epoch 57/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4199 - accuracy: 0.8013
Epoch 58/100
398/398 [==============================] - 1s 3ms/step - loss: 0.4195 - accuracy: 0.7985
Epoch 59/100
398/398 [==============================] - 1s 3ms/step - loss: 0.4192 - accuracy: 0.7984
Epoch 60/100
398/398 [==============================] - 1s 3ms/step - loss: 0.4190 - accuracy: 0.7988
Epoch 61/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4189 - accuracy: 0.7990
Epoch 62/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4184 - accuracy: 0.8007
Epoch 63/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4186 - accuracy: 0.7965
Epoch 64/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4187 - accuracy: 0.7973
Epoch 65/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4184 - accuracy: 0.8013
Epoch 66/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4182 - accuracy: 0.8011
Epoch 67/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4182 - accuracy: 0.8000
Epoch 68/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4177 - accuracy: 0.8022
Epoch 69/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4173 - accuracy: 0.8033
Epoch 70/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4175 - accuracy: 0.8003
Epoch 71/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4169 - accuracy: 0.7987
Epoch 72/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4166 - accuracy: 0.8015
Epoch 73/100
398/398 [==============================] - 1s 3ms/step - loss: 0.4164 - accuracy: 0.7999
Epoch 74/100
398/398 [==============================] - 1s 4ms/step - loss: 0.4166 - accuracy: 0.8000
Epoch 75/100
398/398 [==============================] - 1s 3ms/step - loss: 0.4166 - accuracy: 0.7977
Epoch 76/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4167 - accuracy: 0.8007
Epoch 77/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4165 - accuracy: 0.7989
Epoch 78/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4161 - accuracy: 0.7992
Epoch 79/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4162 - accuracy: 0.8023
Epoch 80/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4157 - accuracy: 0.7992
Epoch 81/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4157 - accuracy: 0.8016
Epoch 82/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4159 - accuracy: 0.8005
Epoch 83/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4151 - accuracy: 0.8016
Epoch 84/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4156 - accuracy: 0.8025
Epoch 85/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4149 - accuracy: 0.8012
Epoch 86/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4145 - accuracy: 0.7996
Epoch 87/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4149 - accuracy: 0.8022
Epoch 88/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4148 - accuracy: 0.8029
Epoch 89/100
398/398 [==============================] - 1s 3ms/step - loss: 0.4144 - accuracy: 0.8025
Epoch 90/100
398/398 [==============================] - 1s 4ms/step - loss: 0.4145 - accuracy: 0.8032
Epoch 91/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4140 - accuracy: 0.8025
Epoch 92/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4143 - accuracy: 0.8029
Epoch 93/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4140 - accuracy: 0.8035
Epoch 94/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4130 - accuracy: 0.8048
Epoch 95/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4137 - accuracy: 0.8044
Epoch 96/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4126 - accuracy: 0.8037
Epoch 97/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4127 - accuracy: 0.8043
Epoch 98/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4132 - accuracy: 0.8053
Epoch 99/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4128 - accuracy: 0.8056
Epoch 100/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4127 - accuracy: 0.8044
63/63 [==============================] - 0s 2ms/step - loss: 0.5005 - accuracy: 0.7540
[0.5005117654800415, 0.7540000081062317]
63/63 [==============================] - 0s 1ms/step
Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.75      0.83      1607
           1       0.43      0.75      0.55       393

    accuracy                           0.75      2000
   macro avg       0.68      0.75      0.69      2000
weighted avg       0.83      0.75      0.78      2000